### PR TITLE
Adding support for account deletions/closures.

### PR DESCRIPTION
**Pull request by Thomas-Donaldson**

### CODE REVIEW

**Comment by Thomas-Donaldson** [comment]
Yup, some conflicts as expected. I'll handle these and return to testing.

**Comment by Thomas-Donaldson** [comment]
I've checked and both the detail editing and account closure are still functional, so the issues are probably resolved...
... I can start the see the value of automated unit testing etc now, it's impossible to understand whether a new feature breaks every existing feature...

**Comment by Thomas-Donaldson** [comment]
[Close an account](https://trello.com/c/Wf6K4yOH/11-close-an-account)

**Comment by tzinakos** [comment]
Nice work Thomas! I am merging the Pr

**Pull request merged**
